name: Docker build and push image
run-name: Build and Push ${{ github.repository }} Docker Image

on:
  workflow_call:
    inputs:
      push:
        default: true
        required: false
        type: boolean
        description: 'Should the image be pushed to the registry or not'
      build-args:
        required: false
        description: 'List of build-time variables'
        type: string
      platforms:
        type: string
        required: false
        default: "linux/amd64"
        description: "Comma separated list of target platforms for build"
<<<<<<< HEAD
      secrets:
          PAT:
            description: 'Personal Access Token to get access to other private repos'
            required: true   
=======
    secrets:
      PAT:
        description: 'Personal Access Token to get access to other private repos'
        required: false
>>>>>>> 381c550bb043d19953cc3beece53595da63a65f4
env:
  REGISTRY: ghcr.io

jobs:
  build-push:
    runs-on: ubuntu-latest
    env:
      HAS_PAT: ${{ secrets.PAT != '' }}
    permissions:
      contents: write      
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
      - name: Display structure of downloaded files
        run: ls -R
      - name: Login to GitHub Container Registry with Personal Access Token
        if: ${{ env.HAS_PAT == 'true' }}
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.PAT }}
      - name: Login to GitHub Container Registry with Github Token
        if: ${{ env.HAS_PAT == 'false' }}
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository }}
          tags: |
            type=ref,event=branch,suffix=-latest
            type=ref,event=branch,suffix=-${{ github.run_number }}
            type=ref,event=tag
            type=semver,pattern={{version}}
            type=semver,pattern={{version}}-latest
            type=semver,pattern={{version}}-${{ github.run_number }}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: ${{ inputs.push }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: ${{ inputs.build-args }}
          platforms: ${{ inputs.platforms }}
