name: NPM Build

run-name: Build ${{ github.repository }} NPM Package

on:
  workflow_call:
    inputs:
      node-version:
        required: false
        description: 'Version Spec of the version to use. Examples: 12.x, 10.15.1, >=10.15.0.'
        default: '20'
        type: string
      client-path:
        required: false
        description: 'Set the location for the package.json'
        type: string
        default: '.'
      build-name:
        required: false
        description: 'Set the name of the build directory'
        default: 'dist'
        type: string
      build-force:
        required: false
        description: 'Force build via --force option'
        default: false
        type: boolean
      run-tests:
        required: false
        default: true
        description: 'Execute tests'
        type: boolean
      artifact-name:
        required: false
        default: 'dist'
        type: string
        description: 'Specify the name the artifact will be published'
      artifact-path:
        required: false
        default: '.'
        type: string
        description: 'Specify the path where the artifact will be found it will be suffixed with the build name'
      script-name:
        required: false
        type: string
        description: 'Script name to build to be executed to build the Application'
        default: 'build'
      build-envs:
        required: false
        type: string
        description: 'Environment variables used for the build'
        default: ''

jobs:
  npm-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup node and npm
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}
          registry-url: "https://npm.pkg.github.com"
          scope: '@westdeutscherrundfunkkoeln'
      - name: Install dependencies
        if: ${{ inputs.build-force == false }}
        run: npm ci --ignore-scripts --prefix ${{ inputs.client-path }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Install dependencies --force
        if: ${{ inputs.build-force == true }}
        run: npm ci --force --ignore-scripts --prefix ${{ inputs.client-path }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}    
      - name: Test Application
        if: ${{ inputs.run-tests == true }}
        run: npm run test --if-present --prefix ${{ inputs.client-path }}
      - name: Build Application
        run: ${{ inputs.build-envs }} npm run ${{ inputs.script-name }} --prefix ${{ inputs.client-path }}

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.artifact-name }}
          path: ${{ inputs.artifact-path }}/${{ inputs.build-name }}
