name: YARN Build

run-name: Build ${{ github.repository }} YARN Package

on:
  workflow_call:
    inputs:
      node-version:
        required: false
        description: 'Version Spec of the version to use. Examples: 12.x, 10.15.1, >=10.15.0.'
        default: '20'
        type: string
      client-path:
        required: false
        description: 'Set the location for the package.json'
        type: string
        default: '.'
      build-name:
        required: false
        description: 'Set the name of the build directory'
        default: 'dist'
        type: string
      build-force:
        required: false
        description: 'Force build via --force option'
        default: false
        type: boolean
      run-tests:
        required: false
        default: true
        description: 'Execute tests'
        type: boolean
      artifact-name:
        required: false
        default: 'dist'
        type: string
        description: 'Specify the name the artifact will be published'
      artifact-path:
        required: false
        default: '.'
        type: string
        description: 'Specify the path where the artifact will be found it will be suffixed with the build name'
      script-name:
        required: false
        type: string
        description: 'Script name to build to be executed to build the Application'
        default: 'build'
      build-envs:
        required: false
        type: string
        description: 'Environment variables used for the build'
        default: ''

jobs:
  yarn-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
 
      - name: Set Node.js  ${{ inputs.node-version }}
                          # 16.x
        uses: actions/setup-node@v3
        with:
          #node-version:  16.x
          node-version:   ${{ inputs.node-version }} 
      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          cmd: install # will run `yarn install` command
        #  dir:  ${{ inputs.client-path }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }} # if needed
      - name: Build production bundle
        uses: borales/actions-yarn@v4
        with:
          #cmd: build:prod # will run `yarn build:prod` command      
          cmd: run build # will run `yarn build:prod` command 
          dir:  ${{ inputs.client-path }}
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.artifact-name }}
          path: ${{ inputs.artifact-path }}/${{ inputs.build-name }}
